function sys=LaneMergingSim_ControllerWithVirtualHumanref
sys = [];
sys.child = [];
sys.NumDataTypes = 8; 
sys.DataTypes = [];
temp.EnumNames='';
temp.EnumValues = [];
temp.Name = '';
sys.DataTypes = repmat(temp,1,8);
sys.DataTypes(1).Name = 'real_T';
sys.DataTypes(2).Name = 'CAN_DATATYPE';
sys.DataTypes(3).Name = 'int8_T';
sys.DataTypes(4).Name = 'uint32_T';
sys.DataTypes(5).Name = 'uint8_T';
sys.DataTypes(6).Name = 'boolean_T';
sys.DataTypes(7).Name = 'uint16_T';
sys.DataTypes(8).Name = 'struct_blVII4bv6oCEzI3NPXgxmH';
